version: 2.1

description: Workflow de build, test, conteneurisation et d√©ploiement

display:
  source_url: https://github.com/jpvincent1980/P13

orbs:
  python: circleci/python@2.0.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-deps

workflows:
  main:
    jobs:
      - build