version: 2.1
description: Workflow de build, test, conteneurisation et d√©ploiement
display:
  source_url: https://github.com/jpvincent1980/P13
jobs:
  build:
    executor:
      name: python
    steps:
      - checkout
      - run: pip install -r requirements.txt

#  test:
#
#  lint:
#
#  containerize:
#
#  deploy:


#workflows:
#  jobs:
#    - build
#    - test
#    - lint
#    - containerize
#    - deploy

#orbs:
#  python: circleci/python@1.5.0
#  heroku: circleci/heroku@1.2.6
#
#jobs:
#  build-and-test:
#    docker:
#      - image: cimg/python:3.10.2
#    steps:
#      - checkout
#      - python/install-packages:
#          pkg-manager: pip
#      - run:
#          name: Run tests
#          command: pytest
#      - run:
#          name: Run flake8 linting
#          command: flake8
#
#workflows:
#  oc-lettings-workflow:
#    jobs:
#      - build-and-test
#      - heroku/deploy-via-git:
#          requires:
#            - build-and-test
#          filters:
#            branches:
#              only: main
          