version: 2.1

description: Workflow de build, test, conteneurisation et d√©ploiement

display:
  source_url: https://github.com/jpvincent1980/P13

orbs:
  python: circleci/python@0.3.2

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
#          pip-dependency-file: requirements.txt
#          pkg-manager: pip

workflows:
  main:
    jobs:
      - build